#!/usr/bin/env python3

#1) generate combination of numbers 0-9 and A-F
#2) check to see if hexidecimal matches matches the original hash
import hashlib
#creates a maximum number of combinations
from itertools import permutations

og_hash="(INSERT_YOUR_ORIGINAL_HASH_HERE"
flag ="FLAG{READABLETEXT_READABLETEXT_THISPARTISACOMBOFNUMBERSANDLETTERSYOURETRYINGTOFIND}"
hex_lst=['A','B','C','D','E','F','0','1','2','3','4','5','6','7','8','9']

def sha_something():

    comb = permutations(hex_lst,3)
    for i in list(comb):
        i = i[0] + i[1] +i[2]
        
        
        test_flag = ("{READABLETEXT_READABLETEXT_" + str(i) + "}")

  
        sha_512 = hashlib.sha512((test_flag).encode()).hexdigest()
        if sha_512 == og_hash:
            print(test_flag + '-------'  + sha_512)
        
sha_something()
